services:
  # PostgreSQL for production
  postgres:
    image: ankane/pgvector:latest
    container_name: postgres-db
    ports:
      - 5435:5434 
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME} 
      - POSTGRES_USER=${USER_DB} 
      - POSTGRES_PASSWORD=${PASSWORD} 
    networks:
      - api-postgres
    volumes:
      - postgres_local_data:/var/lib/postgresql/data:Z
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql 

  # Go API
  go-api:
    container_name: go-api
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    build: 
      context: ./
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=${MONGO_URI}
      - DB_CONTEXT=${DB_CONTEXT}
      - DB_NAME=${DB_NAME}
      - DB_STRING=${DB_STRING}
      - EMBEDDING_TYPE=${EMBEDDING_TYPE}
      - OLLAMA_URL=http://host.docker.internal:11434
    restart: always
    ports:
      - 3000:3000
    networks:
      - api-postgres

networks:
  api-postgres:
    driver: bridge

volumes:
  postgres_local_data: {}
  mongodb_data: {}